<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="13" passed="0" failed="1" skipped="12">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-18T21:20:14 IST" name="Suite" finished-at="2022-08-18T21:20:58 IST" duration-ms="43772">
    <groups>
      <group name="HomePage">
        <method signature="HomePageTest.validateHomePageAdminLink()[pri:5, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePageAdminLink" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateHomePageLeaveLink()[pri:6, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePageLeaveLink" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateHomePageLogo()[pri:3, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePageLogo" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateHomePagePIMLink()[pri:4, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePagePIMLink" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateHomePageTitle()[pri:1, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePageTitle" class="TestLayer.HomePageTest"/>
        <method signature="HomePageTest.validateHomePageUrl()[pri:2, instance:TestLayer.HomePageTest@4dbb42b7]" name="validateHomePageUrl" class="TestLayer.HomePageTest"/>
      </group> <!-- HomePage -->
      <group name="PIMPage">
        <method signature="PIMPageTest.validateCountryDropDown()[pri:4, instance:TestLayer.PIMPageTest@66f57048]" name="validateCountryDropDown" class="TestLayer.PIMPageTest"/>
        <method signature="PIMPageTest.validateDobDates()[pri:6, instance:TestLayer.PIMPageTest@66f57048]" name="validateDobDates" class="TestLayer.PIMPageTest"/>
        <method signature="PIMPageTest.validateDrivingLicenseDate()[pri:3, instance:TestLayer.PIMPageTest@66f57048]" name="validateDrivingLicenseDate" class="TestLayer.PIMPageTest"/>
        <method signature="PIMPageTest.validateMaritalStatusDropDown()[pri:5, instance:TestLayer.PIMPageTest@66f57048]" name="validateMaritalStatusDropDown" class="TestLayer.PIMPageTest"/>
        <method signature="PIMPageTest.validatePIMNewEmployee()[pri:1, instance:TestLayer.PIMPageTest@66f57048]" name="validatePIMNewEmployee" class="TestLayer.PIMPageTest"/>
        <method signature="PIMPageTest.validatePersonalDetailsInPIMPage()[pri:2, instance:TestLayer.PIMPageTest@66f57048]" name="validatePersonalDetailsInPIMPage" class="TestLayer.PIMPageTest"/>
      </group> <!-- PIMPage -->
      <group name="LoginPage">
        <method signature="LoginPageTest.validateLoginFunctionality()[pri:0, instance:TestLayer.LoginPageTest@2ea41516]" name="validateLoginFunctionality" class="TestLayer.LoginPageTest"/>
      </group> <!-- LoginPage -->
    </groups>
    <test started-at="2022-08-18T21:20:14 IST" name="Test" finished-at="2022-08-18T21:20:58 IST" duration-ms="43772">
      <class name="TestLayer.HomePageTest">
        <test-method signature="validateHomePageTitle()[pri:1, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePageTitle" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePageTitle()[pri:1, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePageTitle()[pri:1, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageTitle -->
        <test-method signature="validateHomePageUrl()[pri:2, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePageUrl" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePageUrl()[pri:2, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePageUrl()[pri:2, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageUrl -->
        <test-method signature="validateHomePageLogo()[pri:3, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePageLogo" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePageLogo()[pri:3, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePageLogo()[pri:3, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageLogo -->
        <test-method signature="validateHomePagePIMLink()[pri:4, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePagePIMLink" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePagePIMLink()[pri:4, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePagePIMLink()[pri:4, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePagePIMLink -->
        <test-method signature="validateHomePageAdminLink()[pri:5, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePageAdminLink" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePageAdminLink()[pri:5, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePageAdminLink()[pri:5, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageAdminLink -->
        <test-method signature="validateHomePageLeaveLink()[pri:6, instance:TestLayer.HomePageTest@4dbb42b7]" started-at="2022-08-18T21:20:58 IST" name="validateHomePageLeaveLink" depends-on-groups="LoginPage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method HomePageTest.validateHomePageLeaveLink()[pri:6, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method HomePageTest.validateHomePageLeaveLink()[pri:6, instance:TestLayer.HomePageTest@4dbb42b7] depends on not successfully finished methods in group "LoginPage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateHomePageLeaveLink -->
      </class> <!-- TestLayer.HomePageTest -->
      <class name="TestLayer.PIMPageTest">
        <test-method signature="validatePIMNewEmployee()[pri:1, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validatePIMNewEmployee" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validatePIMNewEmployee()[pri:1, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validatePIMNewEmployee()[pri:1, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePIMNewEmployee -->
        <test-method signature="validatePersonalDetailsInPIMPage()[pri:2, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validatePersonalDetailsInPIMPage" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validatePersonalDetailsInPIMPage()[pri:2, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validatePersonalDetailsInPIMPage()[pri:2, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validatePersonalDetailsInPIMPage -->
        <test-method signature="validateDrivingLicenseDate()[pri:3, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validateDrivingLicenseDate" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validateDrivingLicenseDate()[pri:3, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validateDrivingLicenseDate()[pri:3, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDrivingLicenseDate -->
        <test-method signature="validateCountryDropDown()[pri:4, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validateCountryDropDown" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validateCountryDropDown()[pri:4, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validateCountryDropDown()[pri:4, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCountryDropDown -->
        <test-method signature="validateMaritalStatusDropDown()[pri:5, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validateMaritalStatusDropDown" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validateMaritalStatusDropDown()[pri:5, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validateMaritalStatusDropDown()[pri:5, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateMaritalStatusDropDown -->
        <test-method signature="validateDobDates()[pri:6, instance:TestLayer.PIMPageTest@66f57048]" started-at="2022-08-18T21:20:58 IST" name="validateDobDates" depends-on-groups="HomePage" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PIMPageTest.validateDobDates()[pri:6, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PIMPageTest.validateDobDates()[pri:6, instance:TestLayer.PIMPageTest@66f57048] depends on not successfully finished methods in group "HomePage"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDobDates -->
      </class> <!-- TestLayer.PIMPageTest -->
      <class name="TestLayer.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestLayer.LoginPageTest@2ea41516]" started-at="2022-08-18T21:20:14 IST" name="setUp" finished-at="2022-08-18T21:20:42 IST" duration-ms="28050" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginFunctionality()[pri:0, instance:TestLayer.LoginPageTest@2ea41516]" started-at="2022-08-18T21:20:42 IST" name="validateLoginFunctionality" finished-at="2022-08-18T21:20:58 IST" duration-ms="15639" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Unable to find element with locator By.id: txtUsername
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-TFVQBT0P', ip: '192.168.1.102', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to find element with locator By.id: txtUsername
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.2.2', revision: '683ccb65d6'
System info: host: 'LAPTOP-TFVQBT0P', ip: '192.168.1.102', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:406)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:398)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy17.getWrappedElement(Unknown Source)
at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:51)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:519)
at UtlisLayer.JSExecutor.enterdatausingJavaScriptExecutor(JSExecutor.java:11)
at PageLayer.LoginPage.loginFunctionality(LoginPage.java:26)
at TestLayer.LoginPageTest.validateLoginFunctionality(LoginPageTest.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginFunctionality -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestLayer.LoginPageTest@2ea41516]" started-at="2022-08-18T21:20:58 IST" name="tearDown" finished-at="2022-08-18T21:20:58 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestLayer.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
